//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoritesKazanSight
    {
        public int Id_Favorites { get; set; }
        public int Id_User { get; set; }
        public int Id_Sight { get; set; }
        public bool IsChosen { get; set; }
    
        public virtual KazanSight KazanSight { get; set; }
        public virtual User User { get; set; }
    }
}
