//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id_Reservation { get; set; }
        public int Id_User { get; set; }
        public int Id_SightSeeing { get; set; }
        public bool IsCanceled { get; set; }
    
        public virtual Sightseeing Sightseeing { get; set; }
        public virtual User User { get; set; }
    }
}
